name: Deploy todo-server
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t groothencoder/testing-backend
      - name: Publish Image to docker hub
        run: docker push groothencoder/testing-backend:latest
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull groothencoder/testing-backend:latest
      - name: Delete old container
        run: docker rm -f bookstore-backend-container
      - name: Run Docker Container
        run: docker run -d -p 3001:3001 --name testing-backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_URL }}' groothencoder/testing-backend